apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/singhajeet79/ci-cd-springboot-platform.git
    targetRevision: refactor/production-grade
    path: deployments/base

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
