pipeline {
    agent any

    environment {
        IMAGE = "as35/springboot-app:${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'cd app && ./gradlew clean build'
            }
        }

        stage('Test') {
            steps {
                sh 'cd app && ./gradlew test'
            }
        }

        stage('Static Analysis') {
            steps {
                echo 'Run SonarQube (optional)'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE ./app'
            }
        }

        stage('Push Image') {
            steps {
                sh 'docker push $IMAGE'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" deployments/base/deployment.yaml
                kubectl apply -f deployments/base/
                '''
            }
        }
    }
}
